### ISSUE TITLE
Revised cursor colour

### ISSUE THREAD

**Issue by scottwillmoore** [arcticicestudio/nord-termite#5]
I have applied the following changes to my local copy of the termite config which increase the visibility of the cursor.

The cursor colour uses the same colour as the foreground (white text). Therefore when the cursor is placed above white text (this occurs quite frequently), you cannot read the text underneath. Below is an example of this within vim.

![image](https://cloud.githubusercontent.com/assets/9512557/21581517/880a2962-d088-11e6-96e4-a6ca48b346ae.png)

By adjusting the cursor to use the colour `nord6` instead of `nord4`, this increases the brightness of the cursor, and hence fix this problem. Using pure white, `#FFFFFF` results in even more contrast, and hence makes white text even more readable when the cursor is placed over the top.

````bash
# current cursor colour, nord4.
cursor = #D8DEE9
# better visibility cursor colour, nord6.
cursor = #ECEFF4
````

**Comment by arcticicestudio** [comment]
Thanks for your report.
I've created the theme using a IBeam cursor and forgot about the block cursor.
Unfortunately I'm actually not able to test it on my own since I'm using Terminix and my installed 'vte3' package conflicts with the `vte3-ng` and I can not use my i3 based system at the moment.

I did some research and found [this](https://github.com/thestinger/termite/pull/403) PR in the Termite repository which documents the `cursor_foreground` color option.

Can you please try to set the `cursor_foreground` option to `#2E3440` and test if it fixes the problem?
Otherwise try to unset both the `cursor` and `cursor_foreground` to see if the [default behaviour](https://github.com/thestinger/termite/blob/master/config#L36#L39) works fine.
> If both of these are unset, cursor falls back to the foreground color,
and cursor_foreground falls back to the background color.

This should result in a dark foreground color  (`nord0`) when the cursor is visible while blinking and in the default foreground color (`nord4`) when the cursor is not visible.

If both methods are not working I'll create a VirtualBox image to test it, but I think it is easier if you could test it on your system beforehand.

This is how it actually looks like when using a VTE based emulator like [Terminix](https://github.com/gnunn1/terminix) or GNOME Terminal.
![ghi-5-scrcast-gvim](https://cloud.githubusercontent.com/assets/7836623/21586629/6d05e516-d0d3-11e6-9dcb-2ded4a6f5974.gif)

**Comment by scottwillmoore** [comment]
Yep. This is the solution, and a much better solution than what I had proposed.

I did try using an IBeam cursor, however I found that it messed with my mind too much when trying to use Vim. Now I can move back to using a block cursor! Thanks for that. :smile: 

![image](https://cloud.githubusercontent.com/assets/9512557/21587326/1fa7e2fe-d12f-11e6-988e-cb641dfe2f35.png)

**Comment by arcticicestudio** [comment]
Nice to see that it works! 😄 
I'll add the `cursor_foreground` later to the `config` to fix this for all users.
